### ISSUE TITLE
Disclaimer about importing `av` when developing packages

### ISSUE THREAD

**Issue by tylermorganwall** [ropensci/av#15]
I uploaded the latest version of `rayshader` this morning, and was soon blessed by the following email from Brian D Ripley:

```
You have added the strict requirement of 'av', a package which is not 
easy to install - see 
https://cran.r-project.org/web/checks/check_results_rayshader.html . 
And it is not necessary for the package depending on yours, windfarmGA, 
which now cannot be installed without av.

Please use 'av' in Suggests at most
```

If there isn't a way to make the package easy to install (probably referring to Solaris compatibility), I think it would nice to have a disclaimer about this so others don't end up getting emailed by BDR every time they Import the package.

**Comment by jeroen** [comment]
CRAN is a bit arbitrary about these things. And I think BDR was in a bad mood because he had a hard time building ffmpeg (he contacted me as well), but that should be solved now :-)

I think the general idea here makes sense, to avoid strict dependency on non-essential things. However in this case I disagree because I think video support really imporoves rayshader, and it is really quite easy to install on any system (except for perhaps solaris 🤷‍♀ ).
